version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/Chicago"
    commit-message: 
      prefix: "chore: "
      include: "scope"
